if [ -f /etc/bash.bashrc ]; then
  . /etc/bash.bashrc
fi

PS1='\h:\W\$ '

set -o vi

alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias less="less -R"

export EDITOR=vim
export LESSHISTFILE=/dev/null

# Updates an environment variable to include the given path.
update_variable_with_path() {
  local variable_name=$1
  local path=$2
  local delimeter=${3:-:}

  # Check parameters.
  [[ -z $variable_name ]] && return
  [[ -z $path || ! -d $path ]] && return

  local old_value=$(eval "echo \$${variable_name}")

  # Check if path is already in variable_name.
	[[ "$old_value" =~ "$path" ]] && return
   
	# Update the Variable
  if [[ -z $old_value ]]; then
    eval "export ${variable_name}=${path}"
  else
    eval "export ${variable_name}=${old_value}${delimeter}${path}"
  fi
}

for DIR in $(find ~/apps -maxdepth 1 -mindepth 1 -type d); do
  update_variable_with_path PATH ${DIR}/bin
  update_variable_with_path MANPATH ${DIR}/man
  update_variable_with_path MANPATH ${DIR}/share/man
  update_variable_with_path LDLIBRARYPATH ${DIR}/lib
  for PYDIR in ${DIR}/lib/python*/; do
    update_variable_with_path PYTHONPATH $PYDIR
    update_variable_with_path PYTHONPATH ${PYDIR}/site-packages
  done
done
